name: main_action
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install cpplint
    - run: cpplint --filter=-legal/copyright --linelength=120 --extensions=hpp,cpp,h,c,ino --recursive .
  arduino_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: 'update'
  build_ESP8266:
    runs-on: ubuntu-latest
    needs: [cpplint, arduino_lint]
    env:
        SKETCH_NAME: ESP_Blink 
        CORE: esp8266
        BOARD: d1_mini
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: hredan/ESP_Build_Scripts@master
        with:
          sketch-name: 'ESP_Blink'
