name: main_action
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install cpplint
    - run: cpplint --filter=-legal/copyright --linelength=120 --extensions=hpp,cpp,h,c,ino --recursive .
  arduino_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@main
        with:
          library-manager: 'update'
  build_ESP8266:
    runs-on: ubuntu-latest
    needs: [cpplint, arduino_lint]
    env:
        SKETCH_NAME: ESP_Blink 
        CORE: esp8266
        BOARD: d1_mini
    steps:
      - uses: actions/checkout@v4
      - uses: hredan/ESP_Build_Scripts@master
        with:
          sketch-name: ${{env.SKETCH_NAME}}
          core: ${{env.CORE}}
          board: ${{env.BOARD}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.CORE}}_${{env.BOARD}}_${{env.SKETCH_NAME}}.eep
          path: ./${{env.CORE}}_${{env.BOARD}}_${{env.SKETCH_NAME}}.eep
